/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.dkanen

import kotlin.test.Test
import kotlin.test.*

class VariableTest {
    @Test fun `immutable variables can be created`() {
        val x = 1
        assertEquals(1, x)
    }
}
